version: '3'
services: 
    app:
        build: .
        expose: 
            - ${HTTP_PORT}
        environment: 
            - ConnectionStrings:DefaultConnection= ${CONNECTION_STRING}
    proxy:
        build:
            context:  ./nginx
            dockerfile: Dockerfile
        ports:
            - "5050:5050"
            - "44301:44301"
        volumes:
             - /etc/letsencrypt/:/etc/letsencrypt/
        links:
            - app